// Renders the UI icons from the 3D models (dev/icons.html) into public/icons/*.webp
// and writes the list of available keys to src/render/iconKeys.ts.
// Needs the dev server on :5173.
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { chromium } from 'playwright-core';
const browser = await chromium.launch({
  executablePath: '/opt/pw-browsers/chromium',
  args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'],
});
const page = await browser.newPage({ viewport: { width: 1400, height: 1000 } });
page.on('pageerror', (e) => console.log('ERR', e.message));
await page.goto('http://localhost:5173/dev/icons.html');
await page.waitForFunction(() => document.title === 'ready');
const icons = await page.evaluate(() => window.renderIcons());
await page.screenshot({ path: 'screenshots/icons.png', fullPage: true });
await browser.close();
rmSync('public/icons', { recursive: true, force: true });
mkdirSync('public/icons', { recursive: true });
let bytes = 0;
for (const [key, url] of Object.entries(icons)) {
  const buf = Buffer.from(url.split(',')[1], 'base64');
  bytes += buf.length;
  writeFileSync(`public/icons/${key}.webp`, buf);
}
const keys = Object.keys(icons).sort();
writeFileSync(
  'src/render/iconKeys.ts',
  `// Generated by scripts/icons.mjs — icons rendered from the 3D models.\nexport const ICON_KEYS = new Set<string>(${JSON.stringify(keys, null, 2).replace(/"/g, "'")});\n`,
);
console.log(keys.length, 'icons,', Math.round(bytes / 1024), 'KB');
